### ISSUE TITLE
IP is fetched incorrectly

### ISSUE THREAD

**Issue by jojoe77777** [BlockHorizons/NameChanger#1]
https://github.com/BlockHorizons/NameChanger/blob/aba9f9036ae4b04a96c3ec314de6f2075134ddd1/src/BlockHorizons/NameChanger/NameChanger.php#L84

https://github.com/pmmp/PocketMine-MP/blob/f0b4a33e2e8093081bb9b1fd20947e95422f3df3/src/pocketmine/Server.php#L368

server-ip isn't defined anywhere in server files by default (that in itself isn't an issue with NameChanger)
But when it is defined, it's normally "0.0.0.0" or blank

The correct way to get the IP for players to connect to is `Utils::getIP()` (blocking, do it asynchronously)

**Comment by Sandertv** [comment]
Oh damn, didn't know that. Thanks for reporting :p

**Comment by Thunder33345** [comment]
wouldnt using something like this works too?
https://github.com/ThunderDoesPlugins/UserSwitcher/blob/42641d153293a59e945ede890e0c59c40acc8f82/src/Thunder33345/UserSwitcher/UserSwitcher.php#L64-L71
``$connectIp = explode(':',$pk->serverAddress);``
since not everyone servers are port forwarded
and it would be an huge inconvenience for these who didnt
(lol like me testing mine locally)
